### ISSUE TITLE
get_text_length() for custom fonts doesn't work

### ISSUE THREAD

**Issue by ipoyt** [pymupdf/pymupdf-fonts#4]
I want to calculate the text length of text to insert into a Shape (e.g. rectangle) in order to fit the rectangle height.

- fitz.get_text_length accepts only built-in or CJK fonts
- Font.text_length does the same.

If I pass my font to get_text_length() along with a fontfile, it throws an exception that font is unsupported.
How can I calculate a length of a text for a custom font?

Thanks!

**Comment by JorjMcKie** [comment]
You must define a `Font` object for your font, e.g. `font = fitz.Font(filename="myfont.ttf")`. Then you can use method `font.text_length(...)`.

**Comment by ipoyt** [comment]
Hello Jorj! 
Thank you for the reply!

_I've got: `{TypeError}__init__() got an unexpected keyword argument 'filename'`
PyMuPDF version: 1.22.0_

PS: I'm an idiot, sorry! Fixed it!
